version: "3"
services: 

    frontend:
        build: ./zelda-cookbook-frontend
        ports: 
            - "8000:8000"
        depends_on: 
             - backend
    db:
        build: ./postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: zelda_cookbook
        ports: 
            - "5432:5432"
        networks: 
            - app

    backend:
        build: ./zelda-cookbook-backend
        ports:
            -  "3000:3000"
        depends_on: 
            - db
        networks: 
            - app
     



networks:
    app:
        driver: bridge